try:
    x+1
except Exception as err:
    print(err)